### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by mnemocron** [jimtremblay/ghdl-example#1]
I adjusted the Makefile to run locally instead of via Docker. 
[Makefile.txt](https://github.com/jimtremblay/ghdl-example/files/11969575/Makefile.txt)

But it does not seem to work. What is the correct parameter for TESTBENCH?
I see no file being generated except for the work-obj93.cf

```
make TESTBENCH=counter
make compile TESTBENCH=counter
make[1]: Entering directory '/mnt/c/Users/simon/Downloads/ghdl-example'
make[1]: Leaving directory '/mnt/c/Users/simon/Downloads/ghdl-example'
mv: cannot stat 'counter_tb': No such file or directory
```

**Comment by jimtremblay** [comment]
I have adjusted Makefile for latest ghdl version without docker.

You just need to run with `make TESTBENCH=counter`.

You can change WAVEFORM_VIEWER variable in Makefile if you don't have flatpak version installed.

**Comment by jimtremblay** [comment]
@mnemocron Can you confirm it works for you?

**Comment by mnemocron** [comment]
That worked perfectly, thanks!
